window_title        = "Datenlogger Tool"
file_selection      = "Dateiauswahl"
button_go           = "Start"
button_go_wait      = "Bitte Warten.."
button_set_src_file = "Datei.."
button_use_src_dir  = "Gleicher Ordner"
date_selection      = "Zeitbereich"
options             = "Optionen"
button_otemp        = "Ausßentemperatur einzeichnen"
button_ohumidity    = "Außenluftfeuchtigkeit einzeichnen"
output_file         = "Ausgabe"
output_file_placeholder = "Datei auswählen.."
src_file_dialog     = "Datei auswählen"
src_file_extensions = "Logger Dateien (*.txt *.csv *.dbf);; Alle *.*"
save_file_dialog    = "Zieldatei"
wait_dialog_text    = "Datei wird gelesen.."
error_read_in       = "Fehler beim Einlesen der Datei."
done_text           = "Fertig"
start_section       = "Ausführen"
close               = "Schließen"
open_pic            = "Bild öffnen.."
bad_time            = "Fehlerhafte Zeitangabe!"
warning             = "Warnung"
button_idc          = "Egal, weiter!"
warning_ext_data    = "WARN: Fehlerhafte oder fehlende Werte in externen Daten für angegebenen Zeitraum."
infoOutput          = "Informationen"
cache_hit           = "INFO: Verwende bereits vorhandene Datei: {}"
special_err_1       = "Zeitstempelanzahl stimmt nicht mit Datensatzzahl überein."
warn_no_data        = "Warnung, keine Daten für {}"
pg_request          = "Downloading: {}"
info_ig_lines       = "INFO: Ignoriere {} Zeilen ohne Daten am Anfang der Datei"

# plot.py
warn_empty_series   = "WARN: Leere Datenserie (vielleicht falsches Start-/Enddatum?)"
err_empty_series    = "ERR: Alle gewählten Datenserie sind leer."
info_output_path    = "INFO: Output wird gespeichert nach: {}"

# imageutils.py
info_divergence     = "INFO: Seitenverhältnisabweichung zu A4: {:.2f}%"

success             = "INFO: Fertig."
testing_input       = "Info: Eingabedatei wird geprüft..."
testing_input_suc   = "Info: Eingabedatei akzeptiert."
